### PR TITLE
feat(size): add medium

### PR DESCRIPTION
**Pull request by armasson**
# General summary

Add the 'medium' option inside the available Size map and GapSize type

### CODE REVIEW

**Review by gcornut — CHANGES_REQUESTED** [review]
Can you add a CHANGELOG entry ? 
Also we could test the FlexBox gap size in storybook, can you add a story or add a knob in the `Flex` story ? We'll deploy a storybook and test on it

**Comment by armasson** [comment]
> Can you add a CHANGELOG entry ? Also we could test the FlexBox gap size in storybook, can you add a story or add a knob in the `Flex` story ? We'll deploy a storybook and test on it

I've updated the stories and test with a Knobs and a little story for the GapSize. And by doing that I realised that I had to update the scss too 😅

**Review by gcornut — APPROVED** [review]
Looks good, I'll take the test on storybook

**Comment by gcornut** [comment]
Test OK, felxbox gap size medium working as expected

**Pull request merged**
