### PR TITLE
feat/link-preview-styles

### PR DESCRIPTION
**Pull request by hchevallier**
# General summary
This PR adds ellipsis on title and link.

# Screenshots

# Check list

-   [x] (if has style) Add `need: review-integration` label
-   [ ] (if has textual documentation) Add `need: review-doc` label
-   [ ] (if has code) Add `need: review-frontend` label
-   [ ] (if has react) Check through the [react dev check list]
-   [x] (if fix or feature) Add `need: test` label

Check out the [contribution guide] for general guidelines for submissions to the design system.

[contribution guide]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpment-check-list

### CODE REVIEW

**Review by matmkian — CHANGES_REQUESTED** [review]
I'm not sure we should do this... Force ellipsis on plink previews?

**Comment by hchevallier** [comment]
> I'm not sure we should do this... Force ellipsis on plink previews? Or maybe not this way...

Actually, this is already on one line, and it's truncated for now, without ellipsis. And Articles Preview mockups are showing ellipsis on the link (not on the title, but since it was also forced on one line, I assume it should be ellipsed instead of truncated)

**Comment by matmkian** [comment]
Ok let's talk about that @hchevallier, we should do that in a different way...

**Comment by matmkian** [comment]
The element itself should have specific behavior regarding the context... Less code and more understandable.

**Pull request closed without merging**
