### PR TITLE
FIX/LUM-10327: Date picker weeks display

### PR DESCRIPTION
**Pull request by radiuso**
# General summary

fix the display of the calendar. 
Number of weeks were not well compute by `moment-range` 

# Screenshots

Capture d’écran 2020-06-24 à 15 39 59
Capture d’écran 2020-06-24 à 15 40 04

# Check list

-   [ ] (if has style) Add `need: review-integration` label
-   [ ] (if has textual documentation) Add `need: review-doc` label
-   [ ] (if has code) Add `need: review-frontend` label
-   [ ] (if has react) Check through the [react dev check list]
-   [ ] (if fix or feature) Add `need: test` label

Check out the [contribution guide] for general guidelines for submissions to the design system.

[contribution guide]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpment-check-list

### CODE REVIEW

**Comment by radiuso** [comment]
@gcornut I will need this fix for dhalsim, should we test before releasing?

**Comment by gcornut** [comment]
> @gcornut I will need this fix for dhalsim, should we test before releasing?

@radiuso I'll do a test on the DS storybook. It should be enough. 
Then will merge to master and cherry-pick the fix and release a new v0.22.X so you can update Dhalsim

**Comment by radiuso** [comment]
Good catch @gcornut!
I updated the way of compute days in calendar and avoid using `moment-range.by('week')` function since this lib doesn't handle locale for weeks as expected

**Comment by gcornut** [comment]
Test OK!

**Pull request merged**
