### PR TITLE
Fix/LUM-13688 - Chips color contrast

### PR DESCRIPTION
**Pull request by radiuso**
# General summary

The color contrast on Chip wasn't satisfying a11y rules

# Screenshots

Screenshot 2020-12-29 at 17 06 51

# Check list

-   [x] (if has style) Add `need: review-integration` label
-   [ ] (if has textual documentation) Add `need: review-doc` label
-   [ ] (if has code) Add `need: review-frontend` label
-   [ ] (if has react) Check through the [react dev check list]
-   [ ] (if fix or feature) Add `need: test` label

Check out the [contribution guide] for general guidelines for submissions to the design system.

[contribution guide]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpment-check-list

### CODE REVIEW

**Comment by gcornut** [comment]
LGTM code-wise. We'll need @matmkian validation on the styling/integration aspect

@radiuso Is this a11y issue appearing in both material and lumapps themes? We currently only use the material theme in the product and the lumapps theme color palette is likely to be removed

**Comment by matmkian** [comment]
D3 variant doesn't exists.... Our state rules are applied everywhere, so we have to take the accessibility issue into consideration at the color palette level ans the global states level with @FlorentDinet

**Comment by FlorentDinet** [comment]
Where the colors in the sceenshot come from ?

I've this on the DS [website material theme ](https://design.lumapps.com/product/components/chip/)
Capture d’écran 2021-01-04 à 12 18 01

**Comment by radiuso** [comment]
@FlorentDinet this come from the storybook.
As you see even on the DS site the contrast ratio is not enough. 
We expect a ratio of 4.5:1.
We can change it in the color palette if it is more relevant.

@gcornut I have tested mostly on the lumapps theme

**Comment by matmkian** [comment]
LumApps theme is not used and we cannot change the MaterialDesign color palette quickly. Let's wait to change from Material Design to LumApps theme and set the appropriate color palette.

**Pull request closed without merging**
