### PR TITLE
fix(button): added support for selected state design tokens

### PR DESCRIPTION
**Pull request by SophieChristophe**
BRIDGE-73

# General summary

Button was not using the correct variable for border when selected.
I added some style to take into account the selected state design tokens for the button, so it displays with the right border width variable.

# Screenshots

### CODE REVIEW

**Comment by gcornut** [comment]
Taking the test

**Comment by gcornut** [comment]
Test OK
- Non regression testing ok (test all button variants on SB) ✔️ 
- Customize button border via CSS variables ✔️ 
```css
--lumx-button-emphasis-selected-state-hover-theme-light-border-color: green;
    --lumx-button-emphasis-selected-state-active-theme-light-border-color: blue;
    --lumx-button-emphasis-selected-state-default-theme-light-border-color: red;
    --lumx-button-emphasis-selected-state-hover-theme-dark-border-color: cyan;
    --lumx-button-emphasis-selected-state-active-theme-dark-border-color: violet;
    --lumx-button-emphasis-selected-state-default-theme-dark-border-color: orange;
    --lumx-button-emphasis-selected-state-default-border-width: 2px;
    --lumx-button-emphasis-selected-state-hover-border-width: 3px;
    --lumx-button-emphasis-selected-state-active-border-width: 4px;
 ```
The missing borders on emphasis high and color (other than light/dark) are expected for now. We'll look into improving this later 👍  

https://user-images.githubusercontent.com/939567/197991457-a8fa2ee5-0912-4678-9720-d321aafbb054.mov

**Comment by matmkian** [comment]
I'm working on improving the focus state on another PR. I'm going to handle the issue on my PR.

**Comment by matmkian** [comment]
https://github.com/lumapps/design-system/pull/896

**Pull request closed without merging**
